name: Publish
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew publishAllPublicationsToGithubPackagesRepository -PGitHubPackagesUsername=${{vars.PUBLISHING_USERNAME}} -PGitHubPackagesPassword=${{secrets.PUBLISHING_PAT}}
      - uses: actions/github-script@v8
        with:
          script: |
            const fs = require('fs');
            const tagName = fs.readFileSync('./gradle.properties', 'utf-8').split("\n")
              .find(line => line.startsWith("version="))
              .replace("version=", "")
            const tag = await github.rest.git.createTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: tagName,
              message: `Created from https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`,
              object: context.sha,
              type: 'commit',
            });
            await github.rest.git.createRef({owner: context.repo.owner,repo: context.repo.repo,ref: `refs/tags/${tagName}`,sha: tag.data.sha});